name: "${CONTAINER_NAME}"

services:
  nikola:
    image: "su_blog_nikola:${USER}"
    ports:
      - "127.0.0.1:${LOCAL_PORT}:8000"
    container_name: "${CONTAINER_NAME}"
    restart: always
    command: auto -b -a 0.0.0.0
    volumes:
      - type: bind
        source: ./src
        target: /data
