services:
  nikola:
    image: "su_blog_nikola:${USER}"
    ports:
      - "${LOCAL_PORT}:8000"
    container_name: "${CONTAINER_NAME}"
    restart: always
    command: serve --browser
    volumes:
      - type: bind
        source: ./src
        target: /data
