# https://docs.github.com/ru/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
name: dev su-blog.ru
run-name: Install SU-BLOG dev instance 

on:
  pull_request:
    branches:
    - main

permissions: read-all

jobs:
  test:
    name: Install dev environment
    runs-on: [self-hosted, su-blog, dev]
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests
      run: |
        make test
    - name: Start service
      run: |
        make start
