# https://docs.github.com/ru/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
name: deploy su-blog.ru
run-name: Install SU-BLOG instance 

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    

permissions: read-all

jobs:
  ci:
    if: ${{ github.ref != 'refs/heads/main' }}
    name: Continuous Integration
    runs-on: su-blog
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "Continuous Integration"
    - run: |
        make test
  cd:
    name: Continuous Delivery
    runs-on: su-blog
    needs: ci
    timeout-minutes: 15
    steps:
    - run: |
        echo "Continuous Delivery"
    - run: |
        make start
