# https://docs.github.com/ru/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
name: prod su-blog.ru
run-name: Install SU-BLOG production instance 

on:
  push:
    branches:
    - main

permissions: read-all

jobs:
  deploy:
    name: deploy su-blog.ru
    runs-on: [self-hosted, su-blog, prod]
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start service
      run: |
        make start
